describe("kvim.modules.connections.commands", function()
  it("registers user commands", function()
    local commands = require("kvim.modules.connections.commands")

    commands.setup({})

    local registered = vim.api.nvim_get_commands({})

    assert.is_not_nil(registered.KvimConnections)
    assert.is_not_nil(registered.KvimConnectionsReconnect)
    assert.is_not_nil(registered.KvimConnectionsList)
    assert.is_not_nil(registered.KvimConnectionsAdd)
    assert.is_not_nil(registered.KvimConnectionsDel)
    assert.is_not_nil(registered.KvimConnectionsSetupSshKey)
    assert.is_not_nil(registered.KvimSshConnections)
    assert.is_not_nil(registered.KvimSerialConnections)
    assert.is_not_nil(registered.KvimConnectionShowActive)
    assert.is_not_nil(registered.KvimSSHUploadCurrent)
  end)
end)
